name: Check Terraform Format

on: [push]

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform format check
        run: |
          if ! terraform fmt -check; then
            echo "Terraform code is not properly formatted"
            exit 1
          fi